pref("extensions.printingtoolsng.process.date", true);
pref("extensions.printingtoolsng.process.attachments", true);
pref("extensions.printingtoolsng.headers.setborders", false);
pref("extensions.printingtoolsng.headers.border_style", "border: 1.4px solid black");
pref("extensions.printingtoolsng.headers.hide", false);
pref("extensions.printingtoolsng.headers.truncate", false);
pref("extensions.printingtoolsng.headers.maxchars", 80);
pref("extensions.printingtoolsng.headers.useCcBcc_always", true);
pref("extensions.printingtoolsng.headers.style", false);
pref("extensions.printingtoolsng.headers.size", 10);
pref("extensions.printingtoolsng.hide.inline_attachments", false);
pref("extensions.printingtoolsng.hide.inline_attachments_list", false);
pref("extensions.printingtoolsng.images.hide", false);
pref("extensions.printingtoolsng.printer_printer", "");
pref("extensions.printingtoolsng.printer.persistent", false);
pref("extensions.printingtoolsng.print.silent", false);
pref("extensions.printingtoolsng.print.showprogress", true );
pref("extensions.printingtoolsng.print.just_selection", false);
pref("extensions.printingtoolsng.cite.style", false);
pref("extensions.printingtoolsng.cite.size", 10);
pref("extensions.printingtoolsng.cite.color", "#000000");
pref("extensions.printingtoolsng.process.attachments_with_icon", true);
pref("extensions.printingtoolsng.messages.style", false);
pref("extensions.printingtoolsng.messages.style_apply", 0);
pref("extensions.printingtoolsng.messages.size", 10);
pref("extensions.printingtoolsng.ext_headers.hide", false);
pref("extensions.printingtoolsng.headers.use_background_color", false);
pref("extensions.printingtoolsng.headers.background.color", "#ffffff");
pref("extensions.printingtoolsng.headers.order", "%s,%f,%d,%a,%r1,%r2,%r3");
pref("extensions.printingtoolsng.process.add_p7m_vcf_attach", true);
pref("extensions.printingtoolsng.headers.addfolder", false);
pref("extensions.printingtoolsng.messages.black_text", true);
pref("extensions.printingtoolsng.date.long_format_type", 0);
pref("extensions.printingtoolsng.date.custom_format", "%a, %B %e, %Y %t %H:%M:%S [GMT %z]");
pref("extensions.printingtoolsng.headers.custom_name_value", "");
pref("extensions.printingtoolsng.headers.add_name_type", 0);
pref("extensions.printingtoolsng.change_branch", true);
pref("extensions.printingtoolsng.headers.align", true);
pref("extensions.PrintingToolsNG@cleidigh.kokkini.net.description", "chrome://printingtoolsng/locale/printingtoolsng.properties");
pref("extensions.printingtoolsng.pre_max_length", 90);
pref("extensions.printingtoolsng.images.resize", true);
pref("extensions.printingtoolsng.show_options_button", true);
pref("extensions.printingtoolsng.add_received_date", false);
pref("extensions.printingtoolsng.headers.attachments_per_line", 100);
pref("extensions.printingtoolsng.debug.options", "");
pref("extensions.printingtoolsng.pdf.enable_pdf_output_dir", false);
pref("extensions.printingtoolsng.pdf.output_dir", "");
pref("extensions.printingtoolsng.pdf.custom_filename_format", "${subject}");
pref("extensions.printingtoolsng.pdf.filename.custom_date_format", "%y%m%d");
pref("extensions.printingtoolsng.pdf.filename.prefix", "");
pref("extensions.printingtoolsng.pdf.filename.suffix", "");
pref("extensions.printingtoolsng.pdf.filename.filter_characters", "");
pref("extensions.printingtoolsng.pdf.filename.latinize", false);
pref("extensions.printingtoolsng.pdf.filename.filter_emojis_and_symbols", false);
pref("extensions.printingtoolsng.pdf.filename.max_subject_len", 150);
pref("extensions.printingtoolsng.pdf.filename.max_filename_len", 249);


